---
- name: Ensure install directory is present.
  file:
    path: "{{ glowroot_install_dir }}"
    state: directory

- name: Ensure compressed file is downloaded.
  get_url:
    url: "{{ glowroot_url }}"
    dest: "{{ glowroot_install_dir }}/glowroot.zip"

- name: Ensure downloaded file is uncompressed.
  unarchive:
    src: "{{ glowroot_install_dir }}/glowroot.zip"
    dest: "{{ glowroot_install_dir }}"
    copy: no
    creates: "{{ glowroot_install_dir }}/glowroot/glowroot.jar"

- name: Ensure configuration files are present.
  template:
    src: "{{ item }}.j2"
    dest: "{{ glowroot_install_dir }}/glowroot/{{ item }}"
  with_items:
  - 'admin.json'
  - 'config.json'
