---
- name: Ensure prerequisite packages are present.
  apt:
    pkg: 'unzip'
    state: present

- name: Ensure install directory is present.
  file:
    path: "{{ glowroot_install_dir }}"
    state: directory

- name: Ensure compressed file is downloaded.
  get_url:
    url: "{{ glowroot_url }}"
    dest: "{{ glowroot_install_dir }}/glowroot.zip"

- name: Ensure downloaded file is uncompressed.
  unarchive:
    src: "{{ glowroot_install_dir }}/glowroot.zip"
    dest: "{{ glowroot_install_dir }}"
    copy: no
    creates: "{{ glowroot_home_dir }}/glowroot.jar"

- name: Ensure configuration files are present.
  template:
    src: "{{ item }}.j2"
    dest: "{{ glowroot_home_dir }}/{{ item }}"
  with_items:
  - 'admin.json'
  - 'config.json'

- name: Ensure Glowroot group is present.
  group:
    name: "{{ glowroot_group }}"
    state: present

- name: Ensure Glowroot user is present.
  user:
    name: "{{ glowroot_owner }}"
    state: present

- name: Ensure Glowroot directory ownership.
  file:
    path: "{{ glowroot_home_dir }}"
    owner: "{{ glowroot_owner }}"
    group: "{{ glowroot_group }}"
    mode: 'g+w'
    recurse: yes
    state: directory

- name: Add users to the Glowroot group.
  user:
    name:   "{{ item }}"
    groups: "{{ glowroot_group }}"
    append: yes
  with_items: "{{ glowroot_group_members }}"
  when: glowroot_group_members is defined
